//
//  SCGCodeEngine.swift
//  StratumCAM
//
//  Created by Cristian Baluta on 10.09.2026.
//

import Foundation

public struct SCGCodeEngine {

    public init() {}

    /// Converts generated toolpaths into standard CNC G-code instructions.
    public func generateGCode(from toolpaths: [SC.OutputToolpath], settings: SC.MachineSettings) -> String {

        var lines: [String] = []

        // Header
        lines.append("%")
        lines.append("(Generated by StratumCAM)")
        lines.append("G21 (Units: mm)")
        lines.append("G90 (Absolute Distance Mode)")
        lines.append("G17 (XY Plane Selection)")
        lines.append("G00 Z\(String(format: "%.3f", settings.safeZ)) (Move to Safe Z)")
        lines.append("M03 S\(Int(settings.cutting.spindleSpeed)) (Spindle On)")

        // Toolpaths
        for toolpath in toolpaths {

            let isDrilling: Bool = {
                if case .drilling = toolpath.operation {
                    return true
                }
                return false
            }()

            // Step 2C.2: boring's dwell lives on the operation itself (`dwellTime`), not
            // on `MachineSettings.dwell` the way drilling's does, since it's specific to
            // this one bore rather than a machine-wide default.
            let boringDwellTime: Double? = {
                if case .boring(_, let dwellTime, _) = toolpath.operation {
                    return dwellTime
                }
                return nil
            }()

            // Step 1.5 intentionally handles only the drilling spindle override. Each
            // toolpath carries its own `settings.cutting.spindleSpeed` (set per-operation
            // when the toolpath was generated); if that differs from the machine-wide
            // spindle speed passed into this call, emit an explicit override. Tool changes
            // (`M6`) and general per-tool spindle management remain a Track 4.1 concern.
            if isDrilling,
               abs(toolpath.settings.cutting.spindleSpeed - settings.cutting.spindleSpeed) > 0.000_001 {

                lines.append(
                    "M03 S\(Int(toolpath.settings.cutting.spindleSpeed)) (Drilling spindle speed)"
                )
            }

            for pass in toolpath.passes {

                lines.append("(--- Pass Depth: \(pass.depthZ) ---)")

                // Step 2C.2: boring's dwell happens at the bottom of the bore -- right
                // after the circular interpolation finishes cutting, before any
                // shift-off-center or retract move. Unlike drilling's dwell (always the
                // penultimate waypoint, since a drill cycle never inserts anything after
                // its last cutting move), boring's shift-off-center move (when
                // `shiftRetract` is on) sits between the last cutting move and the final
                // retract, so "penultimate" isn't reliable here -- find the actual last
                // arc waypoint instead.
                let lastArcIndex = pass.waypoints.lastIndex { waypoint in
                    switch waypoint.motion {
                        case .arcCW, .arcCCW: return true
                        default: return false
                    }
                }

                for (index, wp) in pass.waypoints.enumerated() {

                    lines.append(formatWaypoint(wp))

                    // Dwell is emitted after the final cutting move and before
                    // the final retract. MachineSettings expresses dwell in
                    // seconds, and G04 P uses the same value here.
                    //
                    // A normal drilling pass has:
                    //   ... plunge -> final retract
                    //
                    // A peck drilling pass has:
                    //   ... final plunge -> final retract
                    //
                    // Therefore the penultimate waypoint is the final cutting
                    // move in both cases.
                    if isDrilling,
                       index == pass.waypoints.count - 2,
                       let dwell = toolpath.settings.dwell,
                       dwell > 0 {

                        lines.append(
                            "G04 P\(String(format: "%.3f", dwell)) (Drilling dwell)"
                        )
                    }

                    if let boringDwellTime, boringDwellTime > 0, index == lastArcIndex {
                        lines.append(
                            "G04 P\(String(format: "%.3f", boringDwellTime)) (Boring dwell)"
                        )
                    }
                }
            }
        }

        // Footer
        lines.append("G00 Z\(String(format: "%.3f", settings.safeZ))")
        lines.append("M05 (Spindle Stop)")
        lines.append("M30 (Program End)")
        lines.append("%")

        return lines.joined(separator: "\n")
    }

    private func formatWaypoint(_ wp: SC.Waypoint) -> String {

        let x = String(format: "%.3f", wp.position.x)
        let y = String(format: "%.3f", wp.position.y)
        let z = String(format: "%.3f", wp.position.z)
        let f = String(format: "%.1f", wp.feedRate)

        switch wp.motion {

            case .rapid:
                return "G00 X\(x) Y\(y) Z\(z)"

            case .linear:
                return "G01 X\(x) Y\(y) Z\(z) F\(f)"

            case .arcCW(let center):
                let i = String(format: "%.3f", center.x - wp.position.x)
                let j = String(format: "%.3f", center.y - wp.position.y)
                return "G02 X\(x) Y\(y) Z\(z) I\(i) J\(j) F\(f)"

            case .arcCCW(let center):
                let i = String(format: "%.3f", center.x - wp.position.x)
                let j = String(format: "%.3f", center.y - wp.position.y)
                return "G03 X\(x) Y\(y) Z\(z) I\(i) J\(j) F\(f)"
        }
    }
}
