//
//  SCGCodeEngine.swift
//  StratumCAM
//
//  Created by Cristian Baluta on 10.09.2026.
//

import Foundation

public struct SCGCodeEngine {

    public init() {}

    /// Converts generated toolpaths into standard CNC G-code instructions.
    public func generateGCode(from toolpaths: [SC.OutputToolpath], settings: SC.MachineSettings) -> String {

        var lines: [String] = []

        // Header
        lines.append("%")
        lines.append("(Generated by StratumCAM)")
        lines.append("G21 (Units: mm)")
        lines.append("G90 (Absolute Distance Mode)")
        lines.append("G17 (XY Plane Selection)")
        lines.append("G00 Z\(String(format: "%.3f", settings.safeZ)) (Move to Safe Z)")
        lines.append("M03 S\(Int(settings.spindleSpeed)) (Spindle On)")

        // Toolpaths
        for toolpath in toolpaths {

            let isDrilling: Bool = {
                if case .drilling = toolpath.operation {
                    return true
                }
                return false
            }()

            // Step 1.5 intentionally handles only the drilling spindle override.
            // Tool changes (`M6`) and general per-tool spindle management remain
            // a Track 4.1 concern.
            if isDrilling,
               let toolSpindleSpeed = toolpath.tool.spindleSpeed,
               abs(toolSpindleSpeed - settings.spindleSpeed) > 0.000_001 {

                lines.append(
                    "M03 S\(Int(toolSpindleSpeed)) (Drilling spindle speed)"
                )
            }

            for pass in toolpath.passes {

                lines.append("(--- Pass Depth: \(pass.depthZ) ---)")

                for (index, wp) in pass.waypoints.enumerated() {

                    lines.append(formatWaypoint(wp))

                    // Dwell is emitted after the final cutting move and before
                    // the final retract. MachineSettings expresses dwell in
                    // seconds, and G04 P uses the same value here.
                    //
                    // A normal drilling pass has:
                    //   ... plunge -> final retract
                    //
                    // A peck drilling pass has:
                    //   ... final plunge -> final retract
                    //
                    // Therefore the penultimate waypoint is the final cutting
                    // move in both cases.
                    if isDrilling,
                       index == pass.waypoints.count - 2,
                       let dwell = toolpath.settings.dwell,
                       dwell > 0 {

                        lines.append(
                            "G04 P\(String(format: "%.3f", dwell)) (Drilling dwell)"
                        )
                    }
                }
            }
        }

        // Footer
        lines.append("G00 Z\(String(format: "%.3f", settings.safeZ))")
        lines.append("M05 (Spindle Stop)")
        lines.append("M30 (Program End)")
        lines.append("%")

        return lines.joined(separator: "\n")
    }
    
    private func formatWaypoint(_ wp: SC.Waypoint) -> String {

        let x = String(format: "%.3f", wp.position.x)
        let y = String(format: "%.3f", wp.position.y)
        let z = String(format: "%.3f", wp.position.z)
        let f = String(format: "%.1f", wp.feedRate)

        switch wp.motion {

            case .rapid:
                return "G00 X\(x) Y\(y) Z\(z)"

            case .linear:
                return "G01 X\(x) Y\(y) Z\(z) F\(f)"

            case .arcCW(let center):
                let i = String(format: "%.3f", center.x - wp.position.x)
                let j = String(format: "%.3f", center.y - wp.position.y)
                return "G02 X\(x) Y\(y) Z\(z) I\(i) J\(j) F\(f)"

            case .arcCCW(let center):
                let i = String(format: "%.3f", center.x - wp.position.x)
                let j = String(format: "%.3f", center.y - wp.position.y)
                return "G03 X\(x) Y\(y) Z\(z) I\(i) J\(j) F\(f)"
        }
    }
}
